// ====================詞彙庫====================
const wordData = {
  Occupation: {
    words: [
      { cn: "飛機師", en: "pilot" },
      { cn: "郵差", en: "postman" },
      { cn: "護士", en: "nurse" },
      { cn: "醫生", en: "doctor" },
      { cn: "老師", en: "teacher" },
      { cn: "太空人", en: "astronaut" },
      { cn: "警察", en: "policeman" },
      { cn: "消防員", en: "fireman" },
      { cn: "農夫", en: "farmer" },
      { cn: "廚師", en: "chef" },
      { cn: "畫家", en: "artist" },
      { cn: "歌手", en: "singer" },
      { cn: "演員", en: "actor" },
      { cn: "漁夫", en: "fisherman" },
      { cn: "建築工人", en: "builder" },
      { cn: "工程師", en: "engineer" },
      { cn: "司機", en: "driver" },
      { cn: "學生", en: "student" }
    ],
    sentences: {
      cn: [
        "老師|教|學生|知識|。",
        "醫生醫治病人。",
        "護士會幫病人打針。",
        "警察會維持治安。",
        "這是|一位|消防員|，|他|會|救火|又|救人|。",
        "郵差送信到我家。",
        "司機|在|馬路上|駕駛|汽車|。",
        "廚師在廚房烹飪食物。",
        "侍應生|在餐廳|招待|客人|。",
        "理髮師在理髮店修剪頭髮。",
        "清潔工人|在|街道上|清洗|地板|。",
        "飛機師|會|駕駛|飛機|。",
        "太空人|在|火星|探索|生物|。",
        "農夫在田地裡種植蔬菜。",
        "畫家用畫筆繪畫風景。",
        "歌手|在|舞台上|開心的|唱歌|。",
        "演員表演跳舞。",
        "漁夫坐船出海釣魚。",
        "建築工人|搭建|高樓|。",
        "工程師|設計|堅固的|橋樑|。"
      ],
      en: [
        "The teacher teaches students to write.",
        "The doctor helps sick people.",
        "The nurse works in the hospital.",
        "The policeman catches bad people.",
        "The fireman puts out fires.",
        "The postman brings letters to my home.",
        "The driver drives a car on the road.",
        "The chef cooks food in the kitchen.",
        "The waiter works in the restaurant.",
        "The barber makes bread in the barbershop.",
        "The cleaner cleans the street.",
        "The pilot flies a plane.",
        "The astronaut explores Mars.",
        "The farmer grows vegetables in fields.",
        "The artist draws with a brush.",
        "The singer sings happily on stage.",
        "The actor dances on stage.",
        "The fisherman goes fishing by boat.",
        "The builder builds tall buildings.",
        "The engineer makes strong bridges."
      ]
    }
  },
  Place: {
    words: [
      { cn: "圖書館", en: "library" },
      { cn: "機場", en: "airport" },
      { cn: "學校", en: "school" },
      { cn: "超級市場", en: "supermarket" },
      { cn: "巴士站", en: "bus stop" },
      { cn: "火車站", en: "train station" },
      { cn: "公園", en: "park" },
      { cn: "花園", en: "garden" },
      { cn: "銀行", en: "bank" },
      { cn: "泳池", en: "swimming pool" },
      { cn: "街道", en: "street" },
      { cn: "睡房", en: "bedroom" },
      { cn: "客廳", en: "living room" },
      { cn: "廚房", en: "kitchen" },
      { cn: "家裡", en: "home" },
       { cn: "沙灘", en: "beach" },
      { cn: "浴室", en: "bathroom" },
      { cn: "博物館", en: "museum" },
      { cn: "電影院", en: "cinema" },
      { cn: "麵包店", en: "bakery" },
      { cn: "服裝店", en: "clothes shop" },
      { cn: "玩具店", en: "toy shop" },
      { cn: "警察局", en: "police station" },
      { cn: "郵局", en: "post office" },
      { cn: "消防局", en: "fire station" },
      { cn: "書店", en: "book shop" },
      { cn: "醫院", en: "hospital" },
      { cn: "酒店", en: "hotel" },
      { cn: "商場", en: "shopping mall" },
      { cn: "遊樂場", en: "playground" },
      { cn: "餐廳", en: "restaurant" }
    ],
    sentences: {
      cn: [
        "爸爸在客廳看電視。",
        "媽媽|在|廚房|洗菜|。",
        "哥哥在浴室洗澡。",
        "姐姐在書房做功課。",
        "妹妹|在|睡房|睡覺|。",
        "弟弟在餐廳吃飯。",
        "星期日|，|我|和|媽媽|去|超級市場|買東西|。",
        "哥哥在公園裡踢足球。",
        "圖書館要保持安靜。",
        "我們去商場購物。",
        "我在遊樂場玩滑梯。",
        "麵包店|有|好吃的|蛋糕|。",
        "醫院可以幫助生病的人。",
        "我和朋友去電影院看卡通。",
        "郵局可以寄信。",
        "玩具店|有|很多|可愛的|玩具|。",
        "旅行時,我們住在酒店。",
        "花園裡有美麗花朵。",
        "學校是我們學習的地方。",
        "巴士站等車要排隊。"
      ],
      en: [
        "Dad watches TV in the living room.",
        "Mum washes vegetables in the kitchen.",
        "Brother takes a bath in the bathroom.",
        "Little sister sleeps in the bedroom.",
        "She has dinner in the restaurant.",
        "Kids play football in the park.",
        "We must be quiet in the library.",
        "We go shopping at the supermarket.",
        "I play slide in the playground.",
        "This bakery has yummy cakes.",
        "Hospitals help sick people.",
        "We watch movies at the cinema on Monday.",
        "We send letters at the post office.",
        "There are many cute toys in the toy shop.",
        "Hotels are good for trips.",
        "There are pretty flowers in the garden.",
        "School is the place for us to learn.",
        "We queue up at the bus stop."
      ]
    }
  },
  Color: {
    words: [
      { cn: "白色", en: "white" },
      { cn: "藍色", en: "blue" },
      { cn: "綠色", en: "green" },
      { cn: "紫色", en: "purple" },
      { cn: "黑色", en: "black" },
      { cn: "銀色", en: "silver" },
      { cn: "粉紅色", en: "pink" },
      { cn: "深藍色", en: "dark blue" },
      { cn: "淺綠色", en: "light green" },
      { cn: "灰色", en: "grey" },
      { cn: "啡色", en: "brown" },
      { cn: "紅色", en: "red" },
      { cn: "黃色", en: "yellow" },
      { cn: "金色", en: "gold" },
      { cn: "橙色", en: "orange" }
    ],
    sentences: { cn: [], en: [] }
  },
  Nature: { words: [
         { cn: "春天", en: "spring" },
      { cn: "夏天", en: "summer" },
      { cn: "秋天", en: "autumn" },
      { cn: "冬天", en: "winter" },
      { cn: "彩虹", en: "rainbow" },
      { cn: "樹", en: "tree" },
      { cn: "雲", en: "cloud" },
      { cn: "花", en: "flower" },
      { cn: "葉子", en: "leaf" },
      { cn: "太陽", en: "sun" },
      { cn: "草", en: "grass" },
      { cn: "雨", en: "rain" },
      { cn: "海", en: "sea" },
      { cn: "湖", en: "lake" },
      { cn: "河", en: "river" },
      { cn: "水", en: "water" },
      { cn: "風", en: "wind" },
      { cn: "沙", en: "sand" },
      { cn: "閃電", en: "flash" },
      { cn: "打雷", en: "thunder" },
      { cn: "天空", en: "sky" },
      { cn: "田地", en: "filed" },
      { cn: "地面", en: "ground" }
  ], sentences: { cn: [], en: [] } },
  Clothing: { words: [], sentences: { cn: [], en: [] } },
  Object: { words: [], sentences: { cn: [], en: [] } },
  Vegetable: { words: [], sentences: { cn: [], en: [] } },
  Animal: {
    words: [
      { cn: "青蛙", en: "frog" },
      { cn: "老鼠", en: "mouse" },
      { cn: "綿羊", en: "sheep" },
      { cn: "山羊", en: "goat" },
      { cn: "老虎", en: "tiger" },
      { cn: "鴨子", en: "duck" },
      { cn: "雞", en: "chicken" },
      { cn: "猴子", en: "monkey" },
      { cn: "小鳥", en: "bird" },
      { cn: "奶牛", en: "cow" },
      { cn: "馬", en: "horse" },
      { cn: "狗", en: "dog" },
      { cn: "貓", en: "cat" },
      { cn: "斑馬", en: "zebra" },
      { cn: "長頸鹿", en: "giraffe" },
      { cn: "蛇", en: "snake" },
      { cn: "鱷魚", en: "crocodile" },
      { cn: "大象", en: "elephant" },
      { cn: "蜘蛛", en: "spider" },
      { cn: "蜥蜴", en: "lizard" },
      { cn: "鯨魚", en: "whale" },
      { cn: "獅子", en: "lion" },
      { cn: "狐狸", en: "fox" },
      { cn: "貓頭鷹", en: "owl" },
      { cn: "魚", en: "fish" },
      { cn: "金魚", en: "goldfish" },
      { cn: "螞蟻", en: "ant" },
      { cn: "蜜蜂", en: "bee" },
      { cn: "鯊魚", en: "shark" },
      { cn: "豬", en: "pig" },
      { cn: "兔子", en: "rabbit" },
      { cn: "蝸牛", en: "snail" },
      { cn: "樹熊", en: "koala" },
      { cn: "北極熊", en: "polar bear" },
      { cn: "鹿", en: "deer" },
      { cn: "熊", en: "bear" },
      { cn: "海豹", en: "seal" },
      { cn: "蚊", en: "mosquito" },
      { cn: "蝙蝠", en: "bat" },
      { cn: "袋鼠", en: "kangaroo" },
      { cn: "螃蟹", en: "crab" },
      { cn: "豹子", en: "leopard" },
      { cn: "浣熊", en: "raccoon" },
      { cn: "狼", en: "wolf" },
      { cn: "鵝", en: "goose" },
      { cn: "水母", en: "jellyfish" },
      { cn: "八爪魚", en: "octopus" },
      { cn: "猩猩", en: "gorilla" },
      { cn: "草蜢", en: "grasshopper" },
      { cn: "蜻蜓", en: "dragonfly" },
      { cn: "孔雀", en: "peacock" },
      { cn: "甲蟲", en: "beetle" },
      { cn: "海鷗", en: "seagull" },
      { cn: "蝴蝶", en: "butterfly" },
      { cn: "海豚", en: "dolphin" },
      { cn: "恐龍", en: "dinosaur" },
      { cn: "烏龜", en: "turtle" },
      { cn: "鸚鵡", en: "parrot" },
      { cn: "熊貓", en: "panda" },
      { cn: "河馬", en: "hippo" }
    ],
    sentences: {
      cn: [
        "農場裡有山羊，豬和鵝。",
        "老虎是森林之王。",
        "小白兔|愛|吃|青菜|。",
        "蜜蜂|在|花間|採蜜|。",
        "蝸牛|殼子|是|居所|。",
        "鸚鵡模仿人說話。",
        "螞蟻合力搬食物。",
        "甲蟲|在|草上|爬呀爬|。",
        "小魚在水中游泳。",
        "小鳥|在|天空中|飛|。",
        "爸爸愛吃豬肉、白菜和米飯。",
        "水母和鯨魚是海洋中的動物。",
        "放假時|，|我|和|媽媽|到|海洋公園|看|大熊貓|。",
        "春天來了，兩隻蝴蝶在飛舞。",
        "小羊喜歡吃青草。"
      ],
      en: [
        "Fish can live in the water.",
        "Rabbit can run fast."
      ]
    }
  },
  Transportation: {
    words: [
      { cn: "單車", en: "bike" },
      { cn: "纜車", en: "cable car" },
      { cn: "直升機", en: "helicopter" },
      { cn: "船", en: "boat" },
      { cn: "輪船", en: "ship" },
      { cn: "火箭", en: "rocket" },
      { cn: "貨車", en: "truck" },
      { cn: "潛水艇", en: "submarine" },
      { cn: "電車", en: "tram" },
      { cn: "火車", en: "train" },
      { cn: "飛機", en: "plane" },
      { cn: "小巴", en: "minibus" },
      { cn: "小貨車", en: "van" },
      { cn: "渡海小輪", en: "ferry" },
      { cn: "巴士", en: "bus" },
      { cn: "私家車", en: "car" },
      { cn: "的士", en: "taxi" },
      { cn: "帆船", en: "sailboat" },
      { cn: "遊艇", en: "yacht" },
      { cn: "摩托車", en: "motorbike" },
      { cn: "地鐵", en: "subway" },
      { cn: "港鐵", en: "MTR" },
      { cn: "熱氣球", en: "hot air balloon" }
    ],
    sentences: {
      cn: [
        "我|坐|私家車|上學|。",
        "巴士站要排隊等巴士。",
        "放假時|,|我和家人|坐火車|去|旅行|。",
        "直升飛機可以用來救火。",
        "飛機在天上飛行。",
        "渡海小輪|行駛|在|海上|。",
        "公園裡|,|小朋友們|在|踩單車|。",
        "的士|可以|帶|我們|回家|。",
        "摩托車在路上向前走。",
        "爸爸|每天|坐地鐵|從|九龍|到|香港島|工作|。",
        "我們|乘坐|山頂纜車|上山|。",
        "宇航員|乘坐|火箭|飛向|太空|。"
      ],
      en: [
        "I go to school by car.",
        "I travel by train on holidays.",
        "The helicopter can put out fires.",
        "The plane flies in the sky.",
        "We ride bikes in the park.",
        "The taxi brings us home.",
        "The small boat floats on the sea.",
        "The motorbike moves along the road.",
        "Dad takes the subway every day.",
        "We take the cable car up the hill.",
        "Astronauts fly to space by rocket."
      ]
    }
  },
  Stationary: { words: [
     { cn: "鉛筆", en: "pencil" },
      { cn: "膠水", en: "glue" },
      { cn: "尺子", en: "ruler" },
      { cn: "筆", en: "pen" },
      { cn: "橡皮擦", en: "eraser" },
      { cn: "蠟筆", en: "crayon" },
      { cn: "訂書機", en: "stapler" },
      { cn: "剪刀", en: "scissors" },
      { cn: "紙張", en: "paper" }
  ], sentences: { cn: [], en: [] } },
  Fruit: { words: [], sentences: { cn: [], en: [] } },
  People: { words: [], sentences: { cn: [], en: [] } },
  Body: {
    words: [
      { cn: "臉", en: "face" },
      { cn: "眼睛", en: "eye" },
      { cn: "嘴巴", en: "mouth" },
      { cn: "鼻子", en: "nose" },
      { cn: "耳朵", en: "ear" },
      { cn: "頭", en: "head" },
      { cn: "頭髮", en: "hair" },
      { cn: "腿", en: "leg" },
      { cn: "手臂", en: "arm" },
      { cn: "手", en: "hand" },
      { cn: "腳", en: "foot" }
    ],
    sentences: {
      cn: [
        "我用眼睛看風景。",
        "我用耳朵聽音樂。",
        "我用鼻子來呼吸。",
        "我用嘴巴來唱歌。",
        "我|用|手|寫字|。",
        "我用腳走路。"
      ],
      en: [
        "Lily has golden hair.",
        "Alex has big blue eyes."
      ]
    }
  },
  All: { words: [], sentences: { cn: [], en: [] } }
};

const catNameMap = {
  Color: "顏色",
  Nature: "大自然",
  Clothing: "衣服",
  Object: "物件",
  Vegetable: "蔬菜",
  Place: "地點",
  Occupation: "職業",
  Animal: "動物",
  Transportation: "交通",
  Stationary: "文具",
  Fruit: "水果",
  People: "人物",
  Body: "身體",
  All: "全部詞彙"
};
