// ====================詞彙庫====================
const wordData = {
  Occupation: [
    { cn: "飛機師", en: "pilot" },
    { cn: "郵差", en: "postman" },
    { cn: "護士", en: "nurse" },
    { cn: "醫生", en: "doctor" },
    { cn: "老師", en: "teacher" },
    { cn: "太空人", en: "astronaut" },
    { cn: "警察", en: "policeman" },
    { cn: "消防員", en: "fireman" },
    { cn: "農夫", en: "farmer" },
    { cn: "廚師", en: "chef" },
    { cn: "畫家", en: "artist" },
    { cn: "歌手", en: "singer" },
    { cn: "演員", en: "actor" },
    { cn: "漁夫", en: "fisherman" },
    { cn: "建築工人", en: "builder" },
    { cn: "工程師", en: "engineer" },
    { cn: "司機", en: "driver" },
    { cn: "學生", en: "student" }
  ],
  Place: [
    { cn: "圖書館", en: "library" },
    { cn: "機場", en: "airport" },
    { cn: "學校", en: "school" },
    { cn: "超級市場", en: "supermarket" },
    { cn: "巴士站", en: "bus stop" },
    { cn: "火車站", en: "train station" },
    { cn: "公園", en: "park" },
    { cn: "花園", en: "garden" },
    { cn: "銀行", en: "bank" },
    { cn: "泳池", en: "swimming pool" },
    { cn: "街道", en: "street" },
    { cn: "睡房", en: "bedroom" },
    { cn: "客廳", en: "living room" },
    { cn: "廚房", en: "kitchen" },
    { cn: "家裡", en: "home" },
    { cn: "浴室", en: "bathroom" },
    { cn: "博物館", en: "museum" },
    { cn: "電影院", en: "cinema" },
    { cn: "麵包店", en: "bakery" },
    { cn: "服裝店", en: "clothes shop" },
    { cn: "玩具店", en: "toy shop" },
    { cn: "警察局", en: "police station" },
    { cn: "郵局", en: "post office" },
    { cn: "消防局", en: "fire station" },
    { cn: "書店", en: "book shop" },
    { cn: "醫院", en: "hospital" },
    { cn: "酒店", en: "hotel" },
    { cn: "商場", en: "shopping mall" },
    { cn: "遊樂場", en: "playground" },
    { cn: "餐廳", en: "restaurant" }
  ],
  Color: [
    { cn: "白色", en: "white" },
    { cn: "藍色", en: "blue" },
    { cn: "綠色", en: "green" },
    { cn: "紫色", en: "purple" },
    { cn: "黑色", en: "black" },
    { cn: "銀色", en: "silver" },
    { cn: "粉紅色", en: "pink" },
    { cn: "深藍色", en: "dark blue" },
    { cn: "淺綠色", en: "light green" },
    { cn: "灰色", en: "grey" },
    { cn: "啡色", en: "brown" },
    { cn: "紅色", en: "red" },
    { cn: "黃色", en: "yellow" },
    { cn: "金色", en: "gold" },
    { cn: "橙色", en: "orange" }
  ],
  Nature: [],
  Clothing: [],
  Object: [],
  Vegetable: [],
  Animal: [
    { cn: "青蛙", en: "frog" },
    { cn: "老鼠", en: "mouse" },
    { cn: "綿羊", en: "sheep" },
    { cn: "山羊", en: "goat" },
    { cn: "老虎", en: "tiger" },
    { cn: "鴨子", en: "duck" },
    { cn: "雞", en: "chicken" },
    { cn: "猴子", en: "monkey" },
    { cn: "小鳥", en: "bird" },
    { cn: "奶牛", en: "cow" },
    { cn: "馬", en: "horse" },
    { cn: "狗", en: "dog" },
    { cn: "貓", en: "cat" },
    { cn: "斑馬", en: "zebra" },
    { cn: "長頸鹿", en: "giraffe" },
    { cn: "蛇", en: "snake" },
    { cn: "鱷魚", en: "crocodile" },
    { cn: "大象 ", en: "elephant" },
    { cn: "蜘蛛", en: "spider" },
    { cn: "蜥蜴", en: "lizard" },
    { cn: "鯨魚", en: "whale" },
    { cn: "獅子", en: "lion" },
    { cn: "狐狸", en: "fox" },
    { cn: "貓頭鷹", en: "owl" },
    { cn: "魚", en: "fish" },
    { cn: "金魚", en: "goldfish" },
    { cn: "螞蟻", en: "ant" },
    { cn: "蜜蜂", en: "bee" },
    { cn: "鯊魚", en: "shark" },
    { cn: "豬", en: "pig" },
    { cn: "兔子", en: "rabbit" },
    { cn: "蝸牛", en: "snail" },
    { cn: "樹熊", en: "koala" },
    { cn: "北極熊", en: "polar bear" },
    { cn: "鹿", en: "deer" },
    { cn: "熊", en: "bear" },
    { cn: "海豹", en: "seal" },
    { cn: "蚊", en: "mosquito" },
    { cn: "蝙蝠", en: "bat" },
    { cn: "袋鼠", en: "kangaroo" },
    { cn: "螃蟹", en: "crab" },
    { cn: "豹子", en: "leopard" },
    { cn: "浣熊", en: "raccoon" },
    { cn: "狼", en: "wolf" },
    { cn: "鵝", en: "goose" },
    { cn: "水母", en: "jellyfish" },
    { cn: "八爪魚", en: "octopus" },
    { cn: "猩猩", en: "gorilla" },
    { cn: "草蜢", en: "grasshopper" },
    { cn: "蜻蜓", en: "dragonfly" },
    { cn: "孔雀", en: "peacock" },
    { cn: "甲蟲", en: "beetle" },
    { cn: "海鷗", en: "seagull" },
    { cn: "蝴蝶", en: "butterfly" },
    { cn: "海豚", en: "dolphin" },
    { cn: "恐龍", en: "dinosaur" },
    { cn: "烏龜", en: "turtle" },
    { cn: "鸚鵡", en: "parrot" },
    { cn: "熊貓", en: "panda" },
    { cn: "河馬", en: "hippo" }
  ],
  Transportation: [],
  Stationary: [],
  Fruit: [],
  People: [],
  Body: [
    { cn: "臉", en: "face" },
    { cn: "眼睛", en: "eye" },
    { cn: "嘴巴", en: "mouth" },
    { cn: "鼻子", en: "nose" },
    { cn: "耳朵", en: "ear" },
    { cn: "頭", en: "head" },
    { cn: "頭髮", en: "hair" },
    { cn: "腿", en: "leg" },
    { cn: "手臂", en: "arm" },
    { cn: "手", en: "hand" },
    { cn: "腳", en: "foot" }
  ],
  All: []
};

const catNameMap = {
  Color: "顏色",
  Nature: "大自然",
  Clothing: "衣服",
  Object: "物件",
  Vegetable: "蔬菜",
  Place: "地點",
  Occupation: "職業",
  Animal: "動物",
  Transportation: "交通",
  Stationary: "文具",
  Fruit: "水果",
  People: "人物",
  Body: "身體",
  All: "全部詞彙"
};

//拆分句子，分類獨立句子
const sentenceGroup = {
  Occupation: {
    cn: [
      "老師教學生知識。",
      "醫生醫治病人。",
      "護士會幫病人打針。",
      "警察會維持治安。",
      "這是一位消防員，他會救火又救人。",
      "郵差送信到我家。",
      "司機在馬路上駕駛汽車。",
      "廚師在廚房烹飪食物。",
      "侍應生在餐廳招待客人。",
      "理髮師在理髮店修剪頭髮。",
      "清潔工人在街道上清洗地板。",
      "飛機師會駕駛飛機。",
      "太空人在火星探索生物。",
      "農夫在田地裡種植蔬菜。",
      "畫家用畫筆繪畫風景。",
      "歌手在舞台上開心唱歌。",
      "演員表演跳舞。",
      "漁夫坐船出海釣魚。",
      "建築工人搭建高樓。",
      "工程師設計堅固的橋樑。"
    ],
    en: [
      "The teacher teaches students to read and write.",
      "The doctor helps sick people.",
      "The nurse works in the hospital.",
      "The policeman catches bad people.",
      "The fireman puts out fires and saves people.",
      "The postman brings letters to my home.",
      "The driver drives a car on the road.",
      "The chef cooks food in the kitchen.",
      "The waiter helps guests in the restaurant.",
      "The barber cuts hair in the barbershop.",
      "The cleaner cleans the street floor.",
      "The pilot flies a plane high up.",
      "The astronaut explores Mars.",
      "The farmer grows vegetables in fields.",
      "The artist draws scenery with a brush.",
      "The singer sings happily on stage.",
      "The actor dances on stage.",
      "The fisherman goes fishing by boat.",
      "The builder builds tall buildings.",
      "The engineer makes strong bridges."
    ]
  },
  Place: {
    cn: [
      "爸爸在客廳看電視。",
      "媽媽在廚房洗菜。",
      "哥哥在浴室洗澡。",
      "姐姐在書房做功課。",
      "妹妹在睡房睡覺。",
      "弟弟在餐廳吃飯。",
      "星期日，我和媽媽去超級市場買東西。",
      "哥哥在公園裡踢足球。",
      "圖書館要保持安靜。",
      "我們去商場購物。",
      "我在遊樂場玩滑梯。",
      "這家麵包店有好吃蛋糕。",
      "醫院可以幫助生病的人。",
      "我和朋友去電影院看卡通。",
      "郵局可以寄信件。",
      "玩具店有很多可愛玩具。",
      "酒店適合外出旅行住。",
      "花園裡有美麗花朵。",
      "學校是我們學習的地方。",
      "巴士站等車要排隊。"
    ],
    en: [
      "Dad watches TV in the living room.",
      "Mum washes vegetables in the kitchen.",
      "Brother takes a bath in the bathroom.",
      "Sister does homework in the study.",
      "Little sister sleeps in the bedroom.",
      "Little brother eats food in the restaurant.",
      "On Sunday, Mum and I go shopping at the supermarket.",
      "Brother plays football in the park.",
      "We must be quiet in the library.",
      "We go shopping at the shopping mall.",
      "I play slide in the playground.",
      "This bakery has yummy cakes.",
      "Hospitals help sick people.",
      "My friend and I watch cartoons at the cinema.",
      "We send letters at the post office.",
      "There are many cute toys in the toy shop.",
      "Hotels are good for trips.",
      "There are pretty flowers in the garden.",
      "School is the place for us to learn.",
      "We queue up at the bus stop."
    ]
  },
  Animal: {
    cn: [
      "農場裡有山羊，豬和鵝。",
      "老虎是森林之王。",
      "小白兔愛吃青菜。",
      "蜜蜂在花間採蜜。",
      "蝸牛殼子是居所。",
      "鸚鵡模仿人說話。",
      "螞蟻合力搬食物。",
      "甲蟲在草上爬呀爬。",
      "小魚在水中游泳。",
      "小鳥在天空中飛。",
      "爸爸愛吃豬肉、白菜和米飯。",
      "水母和鯨魚是海洋中的動物。",
      "假日，我和媽媽到海洋公園看大熊貓",
      "春天來了，兩隻蝴蝶在飛舞。",
      "小羊喜歡吃青草。"
    ],
    en: [
      "Fish can live in the water.",
      "Rabbit can run fast."
    ]
  },
  Color: { cn: [], en: [] },
  Body: {
    cn: [
      "我用眼睛看風景。",
      "我用耳朵聽音樂。",
      "我用鼻子來呼吸。",
      "我用嘴巴來唱歌。",
      "我用手寫字。",
      "我用腳走路。"
    ],
    en: [
      "Lily has golden hair.",
      "Alex has big blue eyes."
    ]
  },
  All: { cn: [], en: [] }
};
